services:
  frontend:
    image: ghcr.io/dronicaplatformservice/droni-react:latest
    container_name: droni-react
    restart: unless-stopped
    ports:
      - '18080:8080'
    networks:
      - traefik_network
    environment:
      - NODE_ENV=production
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

networks:
  traefik_network:
    external: true
