/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardUserRouteImport } from './routes/dashboard.user'
import { Route as AuthNaverCallbackRouteImport } from './routes/auth/naver/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNaverCallbackRoute = AuthNaverCallbackRouteImport.update({
  id: '/auth/naver/callback',
  path: '/auth/naver/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/settings': typeof SettingsRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/settings': typeof SettingsRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/settings': typeof SettingsRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mypage'
    | '/settings'
    | '/dashboard/user'
    | '/auth/naver/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mypage'
    | '/settings'
    | '/dashboard/user'
    | '/auth/naver/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mypage'
    | '/settings'
    | '/dashboard/user'
    | '/auth/naver/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MypageRoute: typeof MypageRoute
  SettingsRoute: typeof SettingsRoute
  DashboardUserRoute: typeof DashboardUserRoute
  AuthNaverCallbackRoute: typeof AuthNaverCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/naver/callback': {
      id: '/auth/naver/callback'
      path: '/auth/naver/callback'
      fullPath: '/auth/naver/callback'
      preLoaderRoute: typeof AuthNaverCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MypageRoute: MypageRoute,
  SettingsRoute: SettingsRoute,
  DashboardUserRoute: DashboardUserRoute,
  AuthNaverCallbackRoute: AuthNaverCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
